### ISSUE TITLE
When availability = offline, the value is reported along with the topic (default mqtt topic/offline) instead of just the "offline" value

### ISSUE THREAD

**Issue by Alexander-Al** [SenMorgan/Air-Quality-Station#1]
Offline Availability is reported with the mqtt topic inside the value (unlike the online example).
When offline is reported, the message is : 
/air-quality-station/offline (instead of just offline) 

When online is reported, the message is : 
online (as expected)

<img width="415" alt="image" src="https://user-images.githubusercontent.com/20604015/196010539-77b14cc9-1b94-416d-b574-a407cf93a199.png">

**Comment by SenMorgan** [comment]
Found wrong unnecessary definition in MQTT_WILL_MESSAGE.
Fixed 5d0fa3c2
